name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        role-duration-seconds: 500
        role-session-name: Github_Action
    - name: DVC install
      uses: iterative/setup-dvc@v1
    - name: Pull
      run: |
        dvc pull
    - name: Analysing the code with pylint
      run: |
        flake8 . --count --show-source --exit-zero --max-line-length=127 --statistics --max-complexity=1
    - name: Test
      run: |
        pytest starter/tests
    
